name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # if self-hosted

      - name: Run PR status check (on pull_request)
        if: github.event_name == 'pull_request'
        run: |
          chmod +x ./sonar-api.sh
          ./sonar-api.sh lucianobustos_sonarqube-cli ${{ github.event.pull_request.number }} status --json
        env:
          SONAR_HOST: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run project overview (on push to main)
        if: github.event_name == 'push' && contains(github.ref, 'refs/heads/main')
        run: |
          chmod +x ./sonar-api.sh
          ./sonar-api.sh lucianobustos_sonarqube-cli --json
        env:
          SONAR_HOST: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
